version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: gopportunities-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: opportunities
    ports:
      - "5432:5432"
    networks:
      - gopportunities

networks:
  gopportunities:
    driver: bridge
